import numpy as up
matrix=np.array([[1,2,3,4,5],[5,6,7,8,9,10]],dtype=np.int64)
print(matrix)
print("\n"*2)
unos=np.zeros((5,5))
print(ceros)
print("\n"*2)
ceros=np,zeros((5,5))
print(ceros)
print("\n"*2)
ran=np.random.random((4,4))
print(ran)
print("\n"*2)
ept=np.empty((5,5))
print(ept)
